package ReverseModule;


/**
* ReverseModule/StringOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ReverseModule.idl
* Monday, April 28, 2025 11:17:30 PM IST
*/

public interface StringOperations extends StringOperationsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface StringOperations
