package ReverseModule;

/**
* ReverseModule/StringOperationsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ReverseModule.idl
* Monday, April 28, 2025 11:17:30 PM IST
*/

public final class StringOperationsHolder implements org.omg.CORBA.portable.Streamable
{
  public ReverseModule.StringOperations value = null;

  public StringOperationsHolder ()
  {
  }

  public StringOperationsHolder (ReverseModule.StringOperations initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ReverseModule.StringOperationsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ReverseModule.StringOperationsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ReverseModule.StringOperationsHelper.type ();
  }

}
