package ReverseModule;


/**
* ReverseModule/StringOperationsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ReverseModule.idl
* Monday, April 28, 2025 11:17:30 PM IST
*/

abstract public class StringOperationsHelper
{
  private static String  _id = "IDL:ReverseModule/StringOperations:1.0";

  public static void insert (org.omg.CORBA.Any a, ReverseModule.StringOperations that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ReverseModule.StringOperations extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ReverseModule.StringOperationsHelper.id (), "StringOperations");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ReverseModule.StringOperations read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_StringOperationsStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ReverseModule.StringOperations value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ReverseModule.StringOperations narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ReverseModule.StringOperations)
      return (ReverseModule.StringOperations)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ReverseModule._StringOperationsStub stub = new ReverseModule._StringOperationsStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ReverseModule.StringOperations unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ReverseModule.StringOperations)
      return (ReverseModule.StringOperations)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ReverseModule._StringOperationsStub stub = new ReverseModule._StringOperationsStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
