package ReverseModule;


/**
* ReverseModule/StringOperationsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ReverseModule.idl
* Monday, April 28, 2025 11:17:30 PM IST
*/

public interface StringOperationsOperations 
{
  String reverse (String str);
} // interface StringOperationsOperations
